### ISSUE TITLE
[IOS]The screen will be black when  initializeMessages be called.

### ISSUE THREAD

**Issue by Yaxian** [biessek/flutter_localization_example#2] opened 2018-09-05 03:25 UTC
Hi, @biessek , I meet a problem, it will cause black screen when this method has been called
```
Future<bool> initializeMessages(String localeName) async {
  var availableLocale = Intl.verifiedLocale(
    localeName,
    (locale) => _deferredLibraries[locale] != null,
    onFailure: (_) => null);
  if (availableLocale == null) {
    return new Future.value(false);
  }
  var lib = _deferredLibraries[availableLocale];
  await (lib == null ? new Future.value(false) : lib());
  initializeInternalMessageLookup(() => new CompositeMessageLookup());
  messageLookup.addLocale(availableLocale, _findGeneratedMessagesFor);
  return new Future.value(true);
}
```
I don't know why.

`flutter doctor`:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.6.0, on Mac OS X 10.13.6 17G65, locale en-CN)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.26.1)
[✓] Connected devices (1 available)

• No issues found!
```

**Comment by biessek** [comment] 2018-11-15 12:15
Please provide more details like ios simulator/device version. I could not reproduce the behaviour. closing due to the space of time passed, I will reopen if necessary

**Closed as completed by biessek** 2018-11-15 12:15 UTC
